apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hola-mibanco
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hola-mibanco.naodeko.site
      secretName: hola-mibanco-tls
  rules:
    - host: hola-mibanco.naodeko.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hola-mibanco
                port:
                  number: 80
